# Generated by Django 4.2.2 on 2023-07-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('grade', models.TextField()),
            ],
        ),
    ]
