# Generated by Django 4.2.2 on 2023-07-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_experience_alter_education_university_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Media_Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.TextField()),
                ('github', models.TextField()),
            ],
        ),
    ]
