# Generated by Django 4.2.2 on 2023-07-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_social_media_links'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social_Media_Links',
            new_name='SocialMedia',
        ),
    ]
