# Generated by Django 4.2.2 on 2023-07-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_rename_social_media_links_socialmedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='github',
            new_name='platform_name',
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='linkedin',
            new_name='url',
        ),
    ]
