# Generated by Django 4.2.2 on 2023-07-09 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_alter_education_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='created_on',
            field=models.DateTimeField(default=datetime.date(2023, 7, 9)),
            preserve_default=False,
        ),
    ]
