# Generated by Django 4.2.2 on 2023-07-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_education_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
