# Generated by Django 4.2.2 on 2023-07-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_personaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='last_name',
            field=models.TextField(max_length=30),
        ),
    ]
