# Generated by Django 4.2.2 on 2023-07-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_alter_socialmedia_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='logo',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='who_i_am',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
