# Generated by Django 4.2.2 on 2023-07-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_personaldata_logo_personaldata_who_i_am'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='who_i_am',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
