# Generated by Django 4.2.2 on 2023-07-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_alter_contact_email_alter_contact_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
