# Generated by Django 4.2.2 on 2023-07-18 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0020_personaldata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldata',
            name='logo',
        ),
    ]
