# Generated by Django 4.2.2 on 2023-07-23 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0024_alter_message_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldata',
            name='logo',
        ),
    ]
