# Generated by Django 4.2.2 on 2023-07-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0025_remove_personaldata_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.PositiveIntegerField(),
        ),
    ]
