# Generated by Django 4.2.2 on 2023-07-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0026_alter_experience_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
