# Generated by Django 4.2.2 on 2023-07-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0028_alter_education_end_date_alter_education_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_current',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
