# Generated by Django 4.2.2 on 2023-07-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0029_education_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
