# Generated by Django 4.2.2 on 2023-07-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0032_alter_personaldata_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='quote',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
