# Generated by Django 4.2.2 on 2023-07-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0033_personaldata_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='quote',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
