# Generated by Django 4.2.2 on 2023-07-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0034_alter_personaldata_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='bday',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
