# Generated by Django 4.2.2 on 2023-07-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0036_alter_personaldata_bday'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
