# Generated by Django 4.2.2 on 2023-07-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0037_personaldata_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='quote01',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='quote02',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='quote03',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='quote04',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='quote05',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
