# Generated by Django 4.2.2 on 2023-07-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0038_personaldata_quote01_personaldata_quote02_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='quote06',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
