# Generated by Django 4.2.2 on 2023-07-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0039_personaldata_quote06'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='address',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
