# Generated by Django 4.2.2 on 2023-07-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0042_alter_portfolioproject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='image',
            field=models.ImageField(upload_to='resume/static/assets/img/portfolio'),
        ),
    ]
